server:
  port: 8081
  include-message: always
  include-stacktrace: never
adapters:
  r2dbc:
    host: localhost
    database: dbsolicitudes
    username: postgres
    password: admin
    schema: public
    port: 5432
  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
logging:
  level:
    root: INFO
services:
    auth:
      base-url: http://localhost:8080